name: Daily README Update

on:
  schedule:
    - cron: '0 0 * * *'  # Esto ejecutará el workflow cada día a medianoche.
  workflow_dispatch:  # Esto permitirá ejecutar el workflow manualmente.

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run update script
        run: node update-readme.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "🖼️ Update README with today's GIF" || echo "No changes to commit"
          git push
